[build]
  command = "npm run build"
  publish = ".next"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_WHATSAPP_NUMBER,NEXT_PUBLIC_SITE_URL,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
